author: Kekec852
description: NPCLib using minecraft NPCs
main: si.minecraftserver.bukkit.npcvillager.test
name: NPCTestLIB
startup: postworld
version: '1.0'
commands:
  npc:
    discription: NPC commands
    usage: /<command>