author: Kekec852
database: false
description: NPCLib using minecraft NPCs
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: si.minecraftserver.bukkit.npctestlib.NPCTestLIB
name: NPCTestLIB
startup: postworld
url: http://plugins.minecraftserver.si/
version: '1.0'
commands:
  npc:
    discription: NPC commands
    usage: /<command>